on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest commit
        id: latest_commit
        run: |
          latest_commit=$(git log -1 --pretty=format:"%H")
          echo "COMMIT_ID=$latest_commit" >> $GITHUB_ENV

      - name: Make POST request
        run: |
          echo "Commit ID: $COMMIT_ID"
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"ref": "master" }' \
            "https://develop-api.zendata.dev/repositories/2d7a8e42-b8d0-4bd7-b0e9-60bb931d87aa/webhook/"
